name: Checkout, Build, Upload Artifact

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE_SECRET: ${{ secrets.GOOGLE_SERVICE_SECRET }}
        run: echo $GOOGLE_SERVICE_SECRET > ./app/google-services.json

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
